### PR TITLE
Home-Page Done

### PR DESCRIPTION
**Pull request by nataliadiaz2**

### CODE REVIEW

**Review by triciasykes — CHANGES_REQUESTED** [review]
Hey there - what are your header and footer tests testing? Should there be 3 items rendered?

**Comment by nataliadiaz2** [comment]
I was trying to test the NavItems on the Header and Footer. I wanted to change the test from Austin's brown m&m's. I wasn't sure at the time if the NavItems should be in quotes or not.

**Review by nataliadiaz2 — COMMENTED** [review]
I was trying to test the NavItems on the Header and Footer. I wanted to change the test from Austin's brown m&m's. I wasn't sure at the time if the NavItems should be in quotes or not.

**Comment by triciasykes** [comment]
Take a look at the ...Heading.text().  Do you want to be testing text?  AIso, looking at the conditional rendering, results will vary so I think is going to get very complex.  You may want to look at testing something else.

**Review by triciasykes — APPROVED** [review]

**Pull request merged**
